### ISSUE TITLE
camera keeps going on off recording mode

### ISSUE THREAD

**Issue by divemasterjm** [briis/securityspy#13]
i have camera that keeps going on and off motion mode (showing recording on/off)

![image](https://user-images.githubusercontent.com/46672242/113179990-8321c700-9250-11eb-940f-b1f1ac99a169.png)

**Comment by divemasterjm** [comment]
switch is every minute on/off

**Comment by briis** [comment]
Issue #14 and this one are caused by the same. The IO module looses connection to your SecuritySpy instance. I am not absolutely sure why. I need time with the Family during the Easter holidays, so I will look at this as soon as I have time.

**Comment by divemasterjm** [comment]
Thanks I will try to dig more 

JuanMa

**Comment by divemasterjm** [comment]
hope you will have nice time with your family, just to keep u informed and i dont forget to tell you, i turn on record motion and actions but only record motion is the one wich is keeping turning on/off constantly, also i have other cameras and they dont have this behaviour.

**Comment by briis** [comment]
I just checked the Log on my test system, that has been running since I released V1.0 and I have no errors or warnings in the log file. So it could be a local thing with that camera you are having issues with. Is the camera you are having issues with, different from the others that run fine? Other HW, networked in a different way (wireless instead of cable) or any other things that sets this camera a part from the others?

And thanks - wife is just out, so I had an hour to look at things 😁

**Comment by divemasterjm** [comment]
Al cameras are The same, wifi conected and SecuritySpy don’t see any problems.
Very strange issue 

JuanMa

**Comment by divemasterjm** [comment]
If you want me to make some tests just tell me

**Comment by briis** [comment]
Closed with V1.0.2

**Comment by divemasterjm** [comment]
brilliant job, no more error logs anymore and stable switches!!!!
thanks
