### ISSUE TITLE
Too many state attribute changes

### ISSUE THREAD

**Issue by maennes** [briis/securityspy#41]
Is there a way to consolidate the many state attribute changes to ones that can more readily be used in automations? I didn't get the expected results from my automations so I took a look at the HA database (MariaDB in my case). The attached table shows 4 events with a confusing list of attribute changes, in particular for event_object.

![Picture1](https://user-images.githubusercontent.com/39273661/171450157-613707b1-fee0-4ab7-9b9a-c6e3296d9ad6.png)

SQL statement used:
SELECT 
    a.entity_id,
    a.last_updated, 
    a.state,
    json_extract(b.shared_attrs, '$.last_tripped_time') AS `last_tripped_time`,
    json_extract(b.shared_attrs, '$.event_length') AS `event_length`,
    json_extract(b.shared_attrs, '$.event_object') AS `event_object`,
    json_extract(b.shared_attrs, '$.event_score_human') AS `event_score_human`,
    json_extract(b.shared_attrs, '$.event_score_vehicle') AS `event_score_vehicle`
FROM `states` a INNER JOIN state_attributes b ON a.attributes_id = b.attributes_id
WHERE a.entity_id = 'binary_sensor.courtyard_motion'
ORDER BY a.state_id
 
SecuritySpy for Home Assistant v1.1.4
Home Assistant Core 2022.5.5
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1

**Comment by luqman** [comment]
I also get similar results when walking past my hallway camera, it sometimes reports "Vehicle" (I can get logs if needed).

Looking at above logs, we have these entries that look wrong

`CLASSIFY HUMAN 100 VEHICLE 100`  > `None`

When both are 100 it should be `MULTIPLE`, `BOTH` or `VEHICLE_HUMAN`, still not a fan tbh but can't think of anything better. 

`CLASSIFY HUMAN 100 VEHICLE 100`  > `Vehicle`
`CLASSIFY HUMAN 100 VEHICLE 2`  > `Vehicle` this looks wrong

Personally, I would get rid of event object and have two extra sensors, something like

`binary_sensor.front_human_detected` > `on` `off` with a score attribute
`binary_sensor.front_vehicle_detected` > `on` `off` with a score attribute

or `on|off` values that only update if gone above/below some configured threshold for each camera
or maybe `sensor.front_human_detected` > `0...100`  this might be more flexible 

I'll leave some feedback on SS forum.

Ideally there should be a `MOTION_START` event , `MOTION` should be considered a raw event, or renamed to MOTION_AREA

So you would end-up with

```
MOTION_START
CLASSIFY
MOTION_AREA
MOTION_AREA
MOTION_AREA
MOTION_END
```

This in theory should result in less state changes. `MOTION_AREA` would then have equivalent `MOTION_AREA` event on HA that would not impact any state.

SS should also have `CLASSIFY` event after `MOTION_END` or maybe a way to manually trigger it. I've had cases where people stand at the front-door and not get notifications after the first one because they stop moving (depends on motion detection setting).

**Comment by briis** [comment]
Thanks for the detailed feedback @luqman. I like your ideas and will see what I can do to implement those. 
The reason I did not implement a minimum classify score is that I thought this would be controlled by SS, but it seems that it always triggers in this integration, so that is one way to minimize this.
