### ISSUE TITLE
Motion stuck on "detected"

### ISSUE THREAD

**Issue by DigitalPals** [briis/securityspy#44]
Hi, 

When my camera (Hikvision DS-2TD1228T-2/QA) triggers an intrusion rule, then Security Spy is triggered via the "Notify Surveillance Center" rule. This works fine, Security Spy sends me a push notification when this happens. 

The SecuritySpy integration for Home Assistant gets triggers and the camera motion detection shows "detected" state. The problem is that this state never changes, it keeps in "detected" state. 

I tried to manually set the state to "off" / "clear", but after a few seconds the state changes to "detected". To make sure SecuritySpy didn't send that state, I closed SecuritySpy and again it changes back to "detected" even though SecuritySpy is offline. 

Could you please help me out here? I'm using this camera for my security system.

**Comment by lucaferrucci** [comment]
hello and thanks for the fantastic integration, I have a similar problem, if in securityspy it does not detect the movement because the sensitivity is low, in fact it does not send the notification or the mail homeassistant receives the movement anyway.
I have activated some automations for the anti-theft Hass detects movements that securityspy ignores, as if it didn't take into account the SS setting.
Can something be done or am I wrong?
Thanks in advance
