### ISSUE TITLE
error loading config

### ISSUE THREAD

**Issue by divemasterjm** [briis/securityspy#5]
hi, i just delete integration and hacs, reinstall everything but after setting up integration i've got the following error

Error
Config flow could not be loaded

also i have no entities just blank

**Comment by briis** [comment]
How is Home Assistant setup and what version are you running of HA?
I have seen once before a problem if Home Assistant was V2021.3.4 but it works on 2021.3.3. I need to figure out what has changed.

And when I develop, I do it on the upcoming release, and here there are no issues.

**Comment by divemasterjm** [comment]
Im on 
Supervisor 2021.3.6
Core-2021.3.4

**Comment by briis** [comment]
Just to check one thing:

Could you edit the `manifest.json` file and remove the line with `version`. So that it looks like this:

```json
{
    "domain": "securityspy",
    "name": "SecuritySpy for Home Assistant",
    "documentation": "https://github.com/briis/securityspy",
    "issue_tracker": "https://github.com/briis/securityspy/issues",
    "config_flow": true,
    "dependencies": [],
    "codeowners": [
        "@briis"
    ],
    "requirements": [
        "pysecspy==1.0.0"
    ]
}
```

The version was mandatory a few versions ago, but I saw one strange error around that, so I just want to try it out.
After the edit, restart HA, and try again

**Comment by divemasterjm** [comment]
same behaviour
no entities
i notice i have to enter sometimes 2-3 times system options
in logs i have


Error setting up entry SecuritySpy for securityspy
8:30:32 AM – custom_components/securityspy/data.py (ERROR) - message first occurred at 8:28:35 AM and shows up 2 times

**Comment by briis** [comment]
Ok. I will have to work now, but will look at again tonight

**Comment by divemasterjm** [comment]
ok, let me know if you want to do some test, i will reinstall old version meanwhile

**Comment by divemasterjm** [comment]
Logger: homeassistant.config_entries
Source: custom_components/securityspy/data.py:48
First occurred: 8:59:28 AM (1 occurrences)
Last logged: 8:59:28 AM

Error setting up entry SecuritySpy for securityspy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/securityspy/__init__.py", line 68, in async_setup_entry
    await secspy_data.async_setup()
  File "/config/custom_components/securityspy/data.py", line 32, in async_setup
    await self.async_refresh()
  File "/config/custom_components/securityspy/data.py", line 48, in async_refresh
    await self._secspyserver.update(force_camera_update=force_camera_update)
  File "/usr/local/lib/python3.8/site-packages/pysecspy/secspy_server.py", line 98, in update
    await self._get_device_list(not self.ws_connection)
  File "/usr/local/lib/python3.8/site-packages/pysecspy/secspy_server.py", line 153, in _get_device_list
    self._process_cameras_json(json_response, server_id, include_events)
  File "/usr/local/lib/python3.8/site-packages/pysecspy/secspy_server.py", line 251, in _process_cameras_json
    process_camera(
  File "/usr/local/lib/python3.8/site-packages/pysecspy/secspy_data.py", line 86, in process_camera
    last_update = int(time.time()) + int(camera["timesincelastmotion"])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by briis** [comment]
What version of SecuritySpy are you running?

**Comment by divemasterjm** [comment]
5.3.2

**Comment by stbrun** [comment]
Hello Bjarne

I have your beta running. SecuritySyp version 5.3.2 and HASSO version core 2021.3.4.

Somehow I’m missing one sensor.motion_recording camera. But I have the binary_sensor.motion and the camera.xxx for that device.

It looks like everything is running. But after switching the motion settings on and off in security spy the HASSO stops working or the sensor.motion_recording gets a long delay in reaction after a change of the state in security spy.

Stefan

--------------------------------------------------------

Am 25.03.2021 um 09:17 schrieb divemasterjm ***@***.***>:


5.3.2

**Comment by stbrun** [comment]
Just one other thing. When open the camera view I don’t get any sound.

Stefan

--------------------------------------------------------

Am 25.03.2021 um 09:57 schrieb Stefan Brun ***@***.***>:

Hello Bjarne

I have your beta running. SecuritySyp version 5.3.2 and HASSO version core 2021.3.4.

Somehow I’m missing one sensor.motion_recording camera. But I have the binary_sensor.motion and the camera.xxx for that device.

It looks like everything is running. But after switching the motion settings on and off in security spy the HASSO stops working or the sensor.motion_recording gets a long delay in reaction after a change of the state in security spy.

Stefan

--------------------------------------------------------

Am 25.03.2021 um 09:17 schrieb divemasterjm ***@***.*** ***@***.***>>:


5.3.2

**Comment by divemasterjm** [comment]
I can’t get it working, how do you installed?
I’ve tried many times but no success, I’ve I go back older version everything works

JuanMa

**Comment by stbrun** [comment]
Hello JunaMa

I just loaded the files to the components directory. Make a reboot. Then go to the integrations and search for SecuritySyp and install the integration. After that enter your SS information. Restart everything again and you should be all set.

See also: https://github.com/briis/securityspy <https://github.com/briis/securityspy> under manual installation.

Hope this helps!

Stefan

--------------------------------------------------------

Am 25.03.2021 um 10:02 schrieb divemasterjm ***@***.***>:


I can’t get it working, how do you installed?
I’ve tried many times but no success, I’ve I go back older version everything works

JuanMa

**Comment by briis** [comment]
@stbrun 
Do you have any local cameras in SecuritySpy? That might explain the missing sensor and can be corrected.
Could you also turn on debugging for securityspy, by selecting the service `Logger: Set level` and then supplying this data:
```yaml
service: logger.set_level
data:
  custom_components.securityspy: debug
```
(or you can enable it permanently in the configuration.yaml file. Then let me know what you get when turning on or off the motion recording.
Stream: Yes, I get the same issue. It seams somehow to be related to the stream component in HA, because when I issue the same command in VLC I get an instant stream with sound. I will need to look more in to this, and see what I can do.

@divemasterjm I am very puzzled why you have this issue. You seem to be running in the same environment as me, and I am not getting it. Yo do however get this error in the log file, and I am not sure if this is stopping the Integration from being setup, so I will fix that, so we can get past this step.

```log
last_update = int(time.time()) + int(camera["timesincelastmotion"])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

So both, stay tuned for Beta 2, later this evening. (I have to do my real job now :))

**Comment by divemasterjm** [comment]
Did the same but not working for me ((((

**Comment by stbrun** [comment]
Hello Bjarne

Thanks for the feedback. Yes the camera is a local webcam on the Mac where SS is running. The other ones are all IP cams and work ok.

Regarding the logger I’m not so used to this. Can you send me a quick step by step how I can get it done for your or maybe you know a good weblink with this information.

Thanks for your help!

Stefan

--------------------------------------------------------

Am 25.03.2021 um 10:24 schrieb Bjarne Riis ***@***.***>:


@stbrun <https://github.com/stbrun>
Do you have any local cameras in SecuritySpy? That might explain the missing sensor and can be corrected.
Could you also turn on debugging for securityspy, by selecting the service Logger: Set level and then supplying this data:

service: logger.set_level
data:
  custom_components.securityspy: debug
(or you can enable it permanently in the configuration.yaml file. Then let me know what you get when turning on or off the motion recording.
Stream: Yes, I get the same issue. It seams somehow to be related to the stream component in HA, because when I issue the same command in VLC I get an instant stream with sound. I will need to look more in to this, and see what I can do.

@divemasterjm <https://github.com/divemasterjm> I am very puzzled why you have this issue. You seem to be running in the same environment as me, and I am not getting it. Yo do however get this error in the log file, and I am not sure if this is stopping the Integration from being setup, so I will fix that, so we can get past this step.

last_update = int(time.time()) + int(camera["timesincelastmotion"])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
So both, stay tuned for Beta 2, later this evening. (I have to do my real job now :))

**Comment by stbrun** [comment]
Hello Bjarne

I get the following error when I add your logger code to configuration file:

Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:454 
Integration: Hass.io (documentation <https://www.home-assistant.io/hassio>, issues <https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22>) 
First occurred: 7:32:40 (3 occurrences) 
Last logged: 7:42:35

Component error: service - Integration 'service' not found. Component error: data - Integration 'data' not found.

Best regards, Stefan 

--------------------------------------------------------

Am 25.03.2021 um 10:24 schrieb Bjarne Riis ***@***.***>:

service: logger.set_level
data:
  custom_components.securityspy: debug

**Comment by divemasterjm** [comment]
Hello Bjarne
just for your info, ive installed a new ha just to test and ive got same error. only your integration runing on new HA

**Comment by briis** [comment]
I have just released a Beta 2. It should fix some of the errors you have seen, but not all. Please try and see if you can install it now.

**Comment by divemasterjm** [comment]
tried on dev and works!!
moving to production i will keep you informed
Thanks!!!!

**Comment by divemasterjm** [comment]
working on production!!
thanks Bjarne

**Comment by divemasterjm** [comment]
the only thing, i have no switch entity for any camera

**Comment by briis** [comment]
I had tried to fix that, hmmm...

One thing, could I get you to open a new issue on each problem you find, so that I can keep track off what has been done and not done. Just start with this one. Thanks

**Comment by divemasterjm** [comment]
done

**Comment by briis** [comment]
Thanks. I will close this issue now, and then update the rest. Just create a new issue when/if you find it.
